### ISSUE TITLE
Fix ecf-grpc console output on Karaf

### ISSUE THREAD

**Issue by scottslewis** [ECF/grpc-RemoteServicesProvider#11]
On equinox, the current impl of togglereflection, addreflection, removereflection shows:

grpc://localhost:50002                       |active

While on karaf these commands show

https://github.com/ECF/grpc-RemoteServicesProvider/issues/6#issuecomment-817186174

The output from equinox is correct, so the impl may have to be adjusted for Karaf usage of console.

**Comment by scottslewis** [comment]
It seems that his is likely a problem with the karaf console implementation, since it works correctly on gogo:

see https://issues.apache.org/jira/browse/KARAF-5750

**Comment by scottslewis** [comment]
I've fixed this in 1.4.2.  Closing.

**Comment by eum2o** [comment]
Looks fine now, thanks!

![image](https://user-images.githubusercontent.com/1593923/114527645-86ea1c00-9c48-11eb-8b35-8de31b52fbfd.png)
