### ISSUE TITLE
karaf-features.xml is outdated

### ISSUE THREAD

**Issue by eum2o** [ECF/grpc-RemoteServicesProvider#5]
https://github.com/ECF/grpc-RemoteServicesProvider/blob/master/build/karaf-features.xml references `https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-socks_4.1.38.Final.jar` 
but 
`io.netty.codec-socks_4.1.38.Final.jar` does not exist. Instead, it should be 
`io.netty.codec-socks_4.1.52.Final.jar`.

**How to Reproduce:**

```
karaf@root()> repo-add https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/karaf-features.xml
karaf@root()> feature:install -v ecf-rs-distribution-grpc
```

which leads to the following files not being downloadable:

```
Error executing command: Error:
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-http2_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.salesforce.servicelibs.rxgrpc-stub_1.0.0.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.salesforce.servicelibs.reactive-grpc-common_1.0.0.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.handler-proxy_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.buffer_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/org.reactivestreams.reactive-streams_1.0.2.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-http_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.handler_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.transport_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.google.protobuf_3.9.0.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-socks_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.resolver_4.1.38.Final.jar
        Error downloading https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.common_4.1.38.Final.jar
```

**Comment by eum2o** [comment]
This is how I locally fixed the `ecf-rs-distribution-grpc-support` feature:

```xml
<feature name="ecf-rs-distribution-grpc-support" version="1.3.3"
	description="ECF Remote Services Grpc Distribution Provider Support. See https://github.com/ECF/grpc-RemoteServicesProvider">
	<feature>ecf-rs-rsa</feature>
	<feature>ecf-rs-console</feature>
	
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.google.gson_2.7.0.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.google.guava_26.0.0.android.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.google.guava.failureaccess_1.0.1.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.google.protobuf_4.0.0.rc-2.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.salesforce.servicelibs.reactive-grpc-common_1.0.1.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/com.salesforce.servicelibs.rxgrpc-stub_1.0.1.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.buffer_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-http_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-http2_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.codec-socks_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.common_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.handler_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.handler-proxy_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.resolver_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.netty.transport_4.1.52.Final.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/io.reactivex.rxjava2.rxjava_2.2.19.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/org.reactivestreams.reactive-streams_1.0.3.jar
	</bundle>
	<bundle>https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/plugins/org.jsr-305_3.0.2.jar
	</bundle>
</feature>
```

**Comment by scottslewis** [comment]
Using your example I've fixed the karaf-features.xml on master.   Please let me know if this doesn't fix things for you and reopen.

Thanks for reporting.

FWIW, I'm hopeful to get 1.3.3 out within a week...with some new example code (i.e. grpc streams usage).

**Comment by eum2o** [comment]
In my snippet above I set the version of the `ecf-rs-distribution-grpc-support` feature to `1.3.3`. I did this locally because I thought it's better to increment the version to make sure the "newer" feature is used. But I'm not sure if you want to use `1.3.3` in this repository. It maybe should be `1.3.2` instead. Maybe it is okay as it is but I at least wanted to mention it in case you see some problem with it.

I btw just noticed that the `karaf-features.xml` of `grpc-RemoteServicesProvider` is (meanwhile?) referenced by the pre-configured  "ecf" repository (http://download.eclipse.org/rt/ecf/RELEASE/site.p2/karaf-features.xml) which makes the step `repo-add https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/karaf-features.xml` in the `readme.md` obsolete as far as I can judge.

**Comment by scottslewis** [comment]
> 
> 
> In my snippet above I set the version of the `ecf-rs-distribution-grpc-support` feature to `1.3.3`. I did this locally because I thought it's better to increment the version to make sure the "newer" feature is used. But I'm not sure if you want to use `1.3.3` in this repository. It maybe should be `1.3.2` instead. Maybe it is okay as it is but I at least wanted to mention it in case you see some problem with it.

No I think it's fine.   My intention is to update grpc soon to get the ProtoReflectionService (which is not in the version of grpc currently being used).

> 
> I btw just noticed that the `karaf-features.xml` of `grpc-RemoteServicesProvider` is (meanwhile?) referenced by the pre-configured "ecf" repository (http://download.eclipse.org/rt/ecf/RELEASE/site.p2/karaf-features.xml) which makes the step `repo-add https://raw.githubusercontent.com/ECF/grpc-RemoteServicesProvider/master/build/karaf-features.xml` in the `readme.md` obsolete as far as I can judge.

Yes, thanks for the report.   I have an update to ECF core (3.14.20) to do this weekend and after that is complete I will work on the update (probably 1.4.0) to the grpc distribution provider.

**Comment by eum2o** [comment]
Hi @scottslewis. We manually updated the `karaf-features.xml` file in the context of this issue to fix some JAR versions.

I wonder if you always manually maintain the `karaf-features.xml` file or if you generate it. While the `karaf-features.xml` file in this repository looks like feasible to manually maintain, there are other `karaf-features.xml` files that are much more complex, for example https://download.eclipse.org/rt/ecf/latest/site.p2/karaf-features.xml and I cannot imagine it's created and maintained manually (it's a Karaf feature file describing bundles of a p2 repository - I need this too!). 

I see the `karaf-maven-plugin` with the `features-generate-descriptor` goal but I think it's based on POM dependencies rather than OSGi/Manifest dependencies. 

The reason I ask: I am developing an OSGi (remote gRPC) service (using PDE/Tycho) and I want to deploy it on Karaf. However, the bundle that implements the service has a lot of (transitive) dependencies (bundles of my company but also dependencies to e.g. [EMF](https://www.eclipse.org/modeling/emf/)) provided by p2 repositories. I am starting to think that this is a show stopper for me (i.e. I need to look for an alternative to Karaf to deploy my remote service). If you have any hint or buzzword I can look for, I'd be very grateful. Or if you tell me that the `karaf-features.xml` file were created manually, it would help me, too (at least I'd know that this is the way). 


----

// Update:
I worked around the problem (how do I get all the transitive dependencies into Karaf?) by creating an RCP product containing all required plug-ins/features, building it with tycho, and finally generating my own `karaf-features.xml` files listing all .jar files in the `target\products\com.foo.myproduct.product\win32\win32\x86_64\myproduct\plugins` folder. This works fine.

Still I'm curious if you create the `karaf-features.xml` file manually or generate it.

**Comment by scottslewis** [comment]
> 
> 
> Hi @scottslewis. We manually updated the `karaf-features.xml` file in the context of this issue to fix some JAR versions.
> 
> I wonder if you always manually maintain the `karaf-features.xml` file or if you generate it. While the `karaf-features.xml` file in this repository looks like feasible to manually maintain, there are other `karaf-features.xml` files that are much more complex, for example https://download.eclipse.org/rt/ecf/latest/site.p2/karaf-features.xml and I cannot imagine it's created and maintained manually (it's a Karaf feature file describing bundles of a p2 repository - I need this too!).

I currently maintain this one (the grpc-RemoteServicesProvider/build/karaf-features.xml file) by hand....although the one on download.eclipse.org is maintained by a script.   You are welcome to use this script, but it's not generalized very well right now.  The script is here:

# Update karaf.xml
items="$(grep 'mvn:org.eclipse.ecf' karaf-features.xml | sed -e 's/<\/\?bundle>//g' -e 's/\s*\(mvn:org.eclipse.ecf\/\S*\).*/\1/')"
for item in $items ; do
        slashcount="$(echo $item | awk -F\/ '{print NF-1}')"
        artifact="$(echo $item | cut -d/ -f2)"
        jar_version="$(find -name "$artifact-*-SNAPSHOT.jar" | grep -v 'remoteservice\.asyncproxy-1' | sed -e "s/.*$1-\(.*\)-SNAPSHOT.jar/\1/")"
        if [ -z "$jar_version" ] ; then
                continue;
        # if slashcount less than 2 then no version specified
        elif [ "$slashcount" -lt 2 ] ; then
                echo "$item --> mvn:org.eclipse.ecf/$artifact"
                sed -i -e "s|$item|mvn:org.eclipse.ecf/$artifact|" karaf-features.xml
        else
                echo "$item --> mvn:org.eclipse.ecf/$artifact/$jar_version"
                sed -i -e "s|$item|mvn:org.eclipse.ecf/$artifact/$jar_version|" karaf-features.xml
        fi
done

I did not write this.

> 
> I see the `karaf-maven-plugin` with the `features-generate-descriptor` goal but I think it's based on POM dependencies rather than OSGi/Manifest dependencies.

Yes....I haven't used this plugin.

> 
> The reason I ask: I am developing an OSGi (remote gRPC) service (using PDE/Tycho) and I want to deploy it on Karaf. However, the bundle that implements the service has a lot of (transitive) dependencies (bundles of my company but also dependencies to e.g. [EMF](https://www.eclipse.org/modeling/emf/)) provided by p2 repositories. I am starting to think that this is a show stopper for me (i.e. I need to look for an alternative to Karaf to deploy my remote service). If you have any hint or buzzword I can look for, I'd be very grateful. 

I've been more than a little disappointed at the tooling support for Karaf (e.g features generation).  I've asked several times on the Karaf mailing list about feature generation...e.g. as part of eclipse + bndtools.   But as far as I know there is nothing there for that.

Or if you tell me that the `karaf-features.xml` file were created manually, it would help me, too (at least I'd know that this is the way).

Currently it is created manually for most of the ECF distribution providers.  Since the one on download.eclipse.org is pretty stable (no new feautres or bundles being added...mostly), then using a script to simply update the version is pretty easy.

> 
> // Update:
> I worked around the problem (how do I get all the transitive dependencies into Karaf?) by creating an RCP product containing all required plug-ins/features, building it with tycho, and finally generating my own `karaf-features.xml` files listing all .jar files in the `target\products\com.foo.myproduct.product\win32\win32\x86_64\myproduct\plugins` folder. This works fine.

Yes that makes sense...good idea!

> 
> Still I'm curious if you create the `karaf-features.xml` file manually or generate it.

Both...although I'm still hoping for better in the future.  If you find something that works better for generation of karaf-features.xml I would appreciate knowing about it.

**Comment by eum2o** [comment]
Hi Scott. Thank you for the detailed answer and your opinion on it! It brought a lot of light into the darkness. Now I know that for one thing I am not alone and for the other thing I am not missing something ;)

> If you find something that works better for generation of karaf-features.xml I would appreciate knowing about it.

Will do for sure!
